export const endpoints = {
  health: '/health',
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    forgotPassword: '/auth/forgot-password',
    resetPassword: '/auth/reset-password',
  },
  public: {
    services: '/services',
    serviceBySlug: (slug) => `/services/${slug}`,
    projects: '/projects',
    projectBySlug: (slug) => `/projects/${slug}`,
    caseStudies: '/case-studies',
    caseStudyBySlug: (slug) => `/case-studies/${slug}`,
    blogs: '/blogs',
    blogBySlug: (slug) => `/blogs/${slug}`,
    blogCategories: '/blog-categories',
    jobs: '/jobs',
    jobBySlug: (slug) => `/jobs/${slug}`,
    jobApply: (slug) => `/jobs/${slug}/apply`,
    workshops: '/workshops',
    workshopCurrent: '/workshops/current',
    workshopBySlug: (slug) => `/workshops/${slug}`,
    workshopRegister: (slug) => `/workshops/${slug}/register`,
    leads: '/leads',
    quotes: '/quotes',
    contact: '/contact',
    team: '/team',
    testimonials: '/testimonials',
    clientLogos: '/client-logos',
    faqs: '/faqs',
    pricing: '/pricing',
    seo: '/seo',
    settings: '/settings/public',
  },
  admin: {
    services: '/admin/services',
    serviceById: (id) => `/admin/services/${id}`,
    projects: '/admin/projects',
    projectById: (id) => `/admin/projects/${id}`,
    caseStudies: '/admin/case-studies',
    caseStudyById: (id) => `/admin/case-studies/${id}`,
    blogs: '/admin/blogs',
    blogById: (id) => `/admin/blogs/${id}`,
    blogCategories: '/admin/blog-categories',
    blogCategoryById: (id) => `/admin/blog-categories/${id}`,
    jobs: '/admin/jobs',
    jobById: (id) => `/admin/jobs/${id}`,
    applications: '/admin/applications',
    applicationById: (id) => `/admin/applications/${id}`,
    workshops: '/admin/workshops',
    workshopById: (id) => `/admin/workshops/${id}`,
    workshopRegistrations: '/admin/workshop-registrations',
    workshopRegistrationById: (id) => `/admin/workshop-registrations/${id}`,
    leads: '/admin/leads',
    leadById: (id) => `/admin/leads/${id}`,
    quotes: '/admin/quotes',
    quoteById: (id) => `/admin/quotes/${id}`,
    contactMessages: '/admin/contact-messages',
    contactMessageById: (id) => `/admin/contact-messages/${id}`,
    team: '/admin/team',
    teamById: (id) => `/admin/team/${id}`,
    testimonials: '/admin/testimonials',
    testimonialById: (id) => `/admin/testimonials/${id}`,
    clientLogos: '/admin/client-logos',
    clientLogoById: (id) => `/admin/client-logos/${id}`,
    faqs: '/admin/faqs',
    faqById: (id) => `/admin/faqs/${id}`,
    pricing: '/admin/pricing',
    pricingById: (id) => `/admin/pricing/${id}`,
    seo: '/admin/seo',
    seoById: (id) => `/admin/seo/${id}`,
    settings: '/admin/settings',
    users: '/admin/users',
    userById: (id) => `/admin/users/${id}`,
    userResetPassword: (id) => `/admin/users/${id}/reset-password`,
    roles: '/admin/roles',
    roleById: (id) => `/admin/roles/${id}`,
    media: '/admin/media',
    mediaUpload: '/admin/media/upload',
    mediaUploadMultiple: '/admin/media/upload-multiple',
    mediaById: (id) => `/admin/media/${id}`,
    dashboardStats: '/admin/dashboard/stats',
    dashboardActivity: '/admin/dashboard/recent-activity',
    auditLogs: '/admin/audit-logs',
  },
};
